### ISSUE TITLE
Options no-cors on Fetch

### ISSUE THREAD

**Issue by Pierozi** [redux-json-api/redux-json-api#109]
Hi There,

Since the recent security policy have deprecated the wildcard `cross-origin` it's not possible anymore for me to request a specific API Server in DEV Mode. We should be able to specify Options of Fetch lib.

Such as `mode: no-cors` but the options are [hardcoded here](https://github.com/dixieio/redux-json-api/blob/master/src/jsonapi.js#L66)

What did you think ?

**Comment by Pierozi** [comment]
Sorry the link was on the wrong place.

[options used into utils](https://github.com/dixieio/redux-json-api/blob/master/src/utils.js#L9)
maybe good to merge here couples user space options ?

**Comment by egeriis** [comment]
Since we're moving to Axios in v2 and the ability to pass options will come with that, we don't see spending too much time on this for v1. But if you want to add a PR for editing the options. That would be welcomed warmly.

Keep in mind the actions for specifying headers. Maybe they could be merged somehow.

**Comment by Pierozi** [comment]
Thanks for your feedback. I will look if `no-cors` is enough and open PR in this case.

**Comment by egeriis** [comment]
Ok, cool :)

**Comment by Nopzen** [comment]
Hi @Pierozi 

Version 2 have been in beta for some time now, as of today current tag is `2.0.0@beta-2` maybe you could see if this would solve your issue ?

**Comment by Pierozi** [comment]
Thanks for the update, will look at v2 at a time and let you know.

**Comment by Nopzen** [comment]
Closing this for now, feel free to reopen if this is still a issue for to @Pierozi in v2.
