### ISSUE TITLE
Relationships lost when future requests don't include relationship

### ISSUE THREAD

**Issue by jbadger** [redux-json-api/redux-json-api#116]
I've been having a problem since I started using this library back in August, which i've worked around by carefully making requests in a specific order or by ensuring all data I need is included, but this has proven to be painful, error prone and inefficient.  I used it as an excuse to "refresh" my data in case it had changed, but my application has finally reached a point where this is no longer possible to maintain and it's becoming slow due to the size of data.

For Example:
1. GET `/articles?include=author`
2. GET `/people`

If a person was an author for a comment and an article, once request number 2 returns I lose the association between articles and people.  This is also very prone to race conditions, so if request 1 takes longer than request 2, then the relationship works as expected.

My Ruby server uses the [jsonapi-serializers](https://github.com/fotinakis/jsonapi-serializers) gem which would return responses similar to the following.

Response 1:

```json
{
  "data": [
    {
      "type": "articles",
      "id": "1",
      "attributes": {
        "title": "JSON API paints my bikeshed!",
        "body": "The shortest article. Ever.",
        "created": "2015-05-22T14:56:29.000Z",
        "updated": "2015-05-22T14:56:28.000Z"
      },
      "relationships": {
        "author": {
          "data": {
            "id": "42",
            "type": "people"
          }
        }
      }
    }
  ],
  "included": [
    {
      "type": "people",
      "id": "42",
      "attributes": {
        "name": "John",
        "age": 80,
        "gender": "male"
      },
      "relationships": {
        "articles": {},
        "comments": {}
      }
    }
  ]
}
```

Response 2:

```json
{
  "data": [
    {
      "type": "people",
      "id": "42",
      "attributes": {
        "name": "John",
        "age": 80,
        "gender": "male"
      },
      "relationships": {
        "articles": {},
        "comments": {}
      }
    }
  ]
}
```

The key is that the server is returning an empty hash for relationships that are defined but were not requested.  They are not returned because it would be less performant and a waste of database queries to lookup the information.

The way i've worked around this is to include `articles` when I fetch all people, but obviously if I have a lot of people and articles this response will be quite large.
1. GET `/articles?include=author`
2. GET `/people?include=articles`

My suggestion would be that if a relationship does not have the `data` key for a relation, and the store has relationship data already, then it shouldn't be changed as the lack of a `data` key is the server saying "There may be a relationship but I wasn't asked for details about it" and the client says "I know there was a relationship and it hasn't been invalidated by the server yet".  Server would be sending `{data: []}` or `{data: null}` to invalidate a relationship.

I've pulled in the 1.7 merge requests locally just to see if this would get resolved by any of the changes but the issue is not resolved.

**Comment by egeriis** [comment]
Your payload is actually not valid. If you look at the [documentation for relationship objects](http://jsonapi.org/format/#document-resource-object-relationships) it states:

> A “relationship object” MUST contain at least one of the following: `links`, `data` or `meta`

That being said, I think our lib would have the same issue if there was a relationship object with only `links` or `meta` :)

I am not sure what is at works here, because the only relationship you have between your `articles` resource and your `people` resource is the `author` relationship. But the second request should not be able to resolve the reverse relationship and thus remove it.

Would be fun to see a breaking test on this.

**Comment by jbadger** [comment]
@egeriis I was actually mistaken above.  Here is a simple test case that reproduces the issue.

```js
const request1 = {
  "data": [
    {
      "type": "articles",
      "id": "1",
      "attributes": {
        "title": "JSON API paints my bikeshed!",
        "body": "The shortest article. Ever.",
        "created": "2015-05-22T14:56:29.000Z",
        "updated": "2015-05-22T14:56:28.000Z"
      },
      "relationships": {
        "author": {
          "data": {
            "id": "42",
            "type": "people"
          }
        }
      }
    }
  ],
  "included": [
    {
      "type": "people",
      "id": "42",
      "attributes": {
        "name": "John",
        "age": 80,
        "gender": "male"
      },
      "relationships": {
        "articles": {},
        "comments": {}
      }
    }
  ]
}

const request2 = {
  "data": [
    {
      "type": "articles",
      "id": "1",
      "attributes": {
        "title": "JSON API paints my bikeshed!",
        "body": "The shortest article. Ever.",
        "created": "2015-05-22T14:56:29.000Z",
        "updated": "2015-05-22T14:56:28.000Z"
      },
      "relationships": {
        "author": {}
      }
    }
  ]
}

describe('Relationships without data key should not be reset', () => {
  it('should append read resources to state', () => {
    const updatedState = reducer(state, apiRead(request1));
    expect(updatedState.articles).toBeAn('object');
    expect(updatedState.articles.data.length).toEqual(1);
    expect(updatedState.articles.data[0].relationships.author).toEqual({data: {id: '42', type: 'people'}});

    const updatedState2 = reducer(updatedState, apiRead(request2));
    expect(updatedState2.articles).toBeAn('object');
    expect(updatedState2.articles.data.length).toEqual(1);
    expect(updatedState2.articles.data[0].relationships.author).toEqual({data: {id: '42', type: 'people'}});
  });
});
```

**Comment by egeriis** [comment]
I see. Would probably solve the issue by adding a condition to that if-sentence, to check if `resource.data` is set?

Would you care to submit a PR? :)

**Comment by dpdawson** [comment]
Not sure if many people care about this issue, but I found it a bit annoying in a project I'm working on, so I patched it. Probably not the best fix, but I think it's at least sound for the situation discussed in this issue.

**Comment by dvidsilva** [comment]
@dpdawson can you share your patch? this is kinda annoying too.

**Comment by zigzackattack** [comment]
@dpdawson -- I'm getting an error at the [Object.assign line of this fix](https://github.com/stonecircle/redux-json-api/pull/125/commits/e4798834ef7fad16c5d9327da0333fa93dd3400e#diff-bc9093eca63267794ab2e7f893904fa5R129).

Seems that when a resource does not include a `relationships` property, Object.assign throws the following error:

```
VM5872:1 Uncaught TypeError: Cannot convert undefined or null to object
    at Object.assign [as default] (<anonymous>)
    at eval (eval at updateOrInsertResource (state-mutation.js?8e75:227), <anonymous>:1:17)
    at updateOrInsertResource (state-mutation.js?8e75:143)
    at Array.reduce (<anonymous>)
    at updateOrInsertResourcesIntoState (state-mutation.js?8e75:208)
    at eval (jsonapi.js?df85:259)
    at eval (handleAction.js?3d1b:27)
    at eval (index.js?ba5a:13)
    at Array.reduce (<anonymous>)
    at eval (index.js?ba5a:12)
```

Any thoughts?

**Comment by egeriis** [comment]
@zigzackattack Good catch. We should probably use `imm.set` instead. Feel free to submit a PR :)

**Comment by dpdawson** [comment]
`Object.assign({}, resource.relationships, relationships);` should work, right?

**Comment by egeriis** [comment]
@dpdawson You would have to assign the return value to `resource.relationships` then. I'd recommend using [object-path-immutable](https://github.com/mariocasciaro/object-path-immutable), since it ensures immutability. It's imported as `imm`.

**Comment by dakota** [comment]
This seems to have been handled in v2.0. Feel free to reopen if it's still an issue.
