### ISSUE TITLE
Best Practice for 422 or 500 Errors

### ISSUE THREAD

**Issue by seattlecyclist** [redux-json-api/redux-json-api#154]
Hi,
This is not an issue exactly but I do not know where to ask my question otherwise(feel free to close)...

I am trying to figure out the best way to handle server side errors, either expected like validations or unexpected like 500s.

I am currently rendering a 422 response code with the following body
```
{"status":422,"error":"Unprocessable Entity","exception":"#\u003cActiveRecord::RecordInvalid: Validation failed: Description can't be blank\u003e"}
```

Using 2.0.0.beta.3... btw... 

How should I handle this error?  my redux action currently looks something like this:
```
    //audience is passed into the action.
    return (dispatch) => {
        dispatch(updateResource(audience));
    }
```

Again, just trying to understand what is the best practice here... does redus-json-api merge in the errors into my state?  Or should I do that?  Other ideas to handle this?

Thanks

**Comment by egeriis** [comment]
redux-json-api doesn't keep a record of error responses. But when you're dispatching e.g. `dispatch(updateResource({ ... }))` the dispatch call will return a Promise. So you can do:

```js
dispatch(updateResource({ ... }))
  .catch(res => console.log(res));
```

This enables you to handle error messages, as the format and handling is something we wanted to avoid being opinionated about.

**Comment by Nopzen** [comment]
@seattlecyclist - Did you find @egeriis answer enough to solve you issue and close this?
