### ISSUE TITLE
resource.type vs collection endpoint uris

### ISSUE THREAD

**Issue by thomaxxl** [redux-json-api/redux-json-api#162]
you seem to resolve the endpoint uri to 
`${apiHost}${apiPath}/${resource.type}/${resource.id}`;

However, per the jsonapi spec this doesn't have to be the case, 
e.g. a resource.type may be "Article" and the uri may be `${apiHost}${apiPath}/articles/${resource.id}`;

Would it be possible to add an optional parameter where we can specify the endpoint please?

**Comment by egeriis** [comment]
@thomaxxl Can you point me to the specific section in the spec about this? Could not find it in my quick glance

**Comment by thomaxxl** [comment]
I understand, I should've been more clear and I'll check the spec again. 

I tried to use this library against my service which uses 
/articles for {"type" : "article" } and I think I checked the spec for that. 

I had to hack your library and I thought it would be convenient to be able to specify the endpoint manually/optionally (where you infer the url from the type)

In this sentence in the spec, the "type(s)" may refer to multiple types being processed by the same endpoint:
"A server MUST return 409 Conflict when processing a POST request in which the resource object’s type is not among the type(s) that constitute the collection represented by the endpoint."

Also, how do you refer to relationship endpoints? 

Maybe I misunderstood the spec though, in which case i'm sorry for bugging you about this.
I'll see if I find a more specific specification.

**Comment by egeriis** [comment]
Yeah, so you're correct in your assumption about how the URL for POST, PATCH and DELETE requests are put together. 

Relationship endpoints is not something we're using behind the scenes right now. You may use them in GET requests though `readEndpoint`, but for that particular method you're specifying the exact endpoint yourself.

I can't find anything in the spec about this right now, but I recall having seen something like plural/singular not mattering, but that it should be consistent. So if you're using singular for your resource object, you should use singular in the URL.

**Comment by thomaxxl** [comment]
I asked this on the jsonapi forum:
https://discuss.jsonapi.org/t/endpoints-vs-types/1265

"Polymorphism is supported in the spec, and even unrelated json:api types can be in the same collections. This is why it’s important you don’t try to infer any information from coincidental likeness in deployment and documents."

**Comment by egeriis** [comment]
I'm not sure I find that conversation to be complete. _michaelhibay_ talks about collections, which implies reading from an endpoint. Using `readEndpoint` from redux-json-api to read from `/my-resources`, doesn't lead redux-json-api to make any assumptions. 

I think there _is_ something actionable though, because instead of infering the URL from the type and ID, we should use `links.self` 🙂
