### ISSUE TITLE
Update state at next readEndpoint

### ISSUE THREAD

**Issue by DimaelVertigo** [redux-json-api/redux-json-api#167]
Hello and happy Programmers day!

So, I make pagination from the server and receive not all data at same time. 
For example: 
When first `readEndpoint()` in `componentDidMount()` my app receive `data[]` (lenght===10). 
Next, I click on the button and wait for the next 10 items. I see it in the `payload`. But `state` collects it and consist of old 10 items + new 10 items. 
`render` shows 20 items. I would like to show only 10 new item without previous.

How I can update `state.tasks.data[]` and have only current `readEndpoint()` result at the moment without concatenation with previous `readEndpoint()` result?

**Comment by egeriis** [comment]
Hi @DimaelVertigo!

redux-json-api is build in the way that it maintains and structures your resources, this has a caveat that it doesn't keep a record of which resources were returned for a particular request.

This is part of the reason I have started working on https://github.com/redux-json-api/react-redux-json-api (name tbd) which helps with all of this while utilizing the awesomeness of having a normalized resource storage in redux 🙂

**Comment by DimaelVertigo** [comment]
Can I access data from `payload` and save them to the different object?

**Comment by dakota** [comment]
Closing as stale.
