### ISSUE TITLE
Action type is undefined

### ISSUE THREAD

**Issue by skyride99** [redux-json-api/redux-json-api#169]
for 
        dispatch(setAccessToken(authToken))

getting

action     {type: undefined, payload: {…}}payload: {Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleH…IzOH0.um7qXa7CzEkYCx8VGnZQIjXrrah0_dzulMinkb2S3X4"}type: undefined__proto__: Object
redux-logger.js:1  error      Error: Actions may not have an undefined "type" property. Have you misspelled a constant?
    at Object.performAction (<anonymous>:1:40795)
    at liftAction (<anonymous>:1:34238)
    at dispatch (<anonymous>:1:38232)
    at redux-logger.js:1
    at index.js:11
    at dispatch (redux.js:563)
    at jsonapi.js:75
    at index.js:8
    at dispatch (redux.js:563)
    at authentication.js:88
redux-logger.js:1  next state {api: {…}, authentication: {…}, globalState: {…}, jobPosts: {…}, modal: {…}, …}
authentication.js:120 @@@@@ in the catch

**Comment by mspae** [comment]
@skyride99  This action creator is out of date. (The documentation hasn't been updated yet)

You need to use the `setAxiosConfig` – See here for an example https://github.com/dvidsilva/redux-json-api-demo/#configuring-the-api-server-options

**Comment by skyride99** [comment]
but i am using 1.7.1, with React 16. 

Only v2 works with react 16?

**Comment by egeriis** [comment]
This is unrelated to React. Very weird that action.type is undefined. I'm curious if you have some middleware which interferes with the actions, I've never heard of this issue before.

**Comment by dakota** [comment]
Closing as stale, feel free to reopen if you are still having the issue.
