### ISSUE TITLE
Is there any known live fork of this repo?

### ISSUE THREAD

**Issue by vicmosin** [redux-json-api/redux-json-api#178]
This one seems to be dead with 3 open PRs and no responses in issues

**Comment by egeriis** [comment]
I don't know of any. The PRs are mostly stale because of the contributors not returning after having it reviewed 🤷‍♂ That said, I myself do not actively maintain this anymore.

**Comment by dakota** [comment]
@vicmosin Been a while, but I have taken over active maintenance.
