### ISSUE TITLE
Add missing support for a complete URL passed as endpoint.

### ISSUE THREAD

**Issue by Nopzen** [redux-json-api/redux-json-api#18]
When passing a complete URL as the endpoint, in this case a pagination.

`"http://my.app/api/v1/companies/1/timelineItems/?page%5Bcache%5D=1xfupzj63rtx&page%5Bpage%5D=2"`

Redux json api should recon. that this is a fully specified URL and just query the URL given from the backend, that it expects, instead of applying it as a endpoint. current situration happens below: 

`"http://my.app/api/v1/http://my.app/api/v1/companies/1/timelineItems/?page%5Bcache%5D=1xfupzj63rtx&page%5Bpage%5D=2"`

**Comment by egeriis** [comment]
For pagination purposes, I think it might even be a solution to add some API for easy navigation between pages.

This is a spec I could see as a proposal for this feature: 

- [x] Be able to easily load data from `next` and `prev` API URLs through `redux-json-api`
- [x] An easy interface from `redux-json-api` to fetch stored data from state, that belongs to `next` and `prev` to avoid unnecessary API calls

There are probably more side effects and possible additions to this feature.

**Comment by egeriis** [comment]
Closing this to urge further discussion to move to #21

**Comment by asrytis** [comment]
This would be a lovely feature. I am consuming data from 2 different hosts and having to dispatch `setEndpointHost(...)` and `setEndpointPath(...)` before every API request feels wrong and is very inconvenient too. In my opinion these two actions shouldn't be needed at all unless there are scenarios that I'm unaware of. 

Compare existing
```javascript
const fetchUsers = () => (dispatch) => {
  dispatch(setEndpointHost(API_HOST1));
  dispatch(setEndpointPath(API_PATH1));
  return dispatch(readEndpoint('users'));
}

const fetchResources = () => (dispatch) => {
  dispatch(setEndpointHost(API_HOST2));
  dispatch(setEndpointPath(API_PATH2));
  return dispatch(readEndpoint('resources'));
}
```
vs new
```javascript
const fetchUsers = () => (dispatch) => {
  return dispatch(readEndpoint(`${API_PATH_1}/users`));
}

const fetchResources = () => (dispatch) => {
  return dispatch(readEndpoint(`${API_PATH_2}/resources`));
}
```
Related: [Dan Abramov on setter actions](https://twitter.com/dan_abramov/status/793379336309071872)

**Comment by egeriis** [comment]
@asrytis That's definitely a reasonable use case. How about pre-configuring hosts and being able to curry `readEndpoint` or be able to provide a configuration ID of some sorts, when dispatching `readEndpoint`?

**Comment by asrytis** [comment]
@egeriis The way I see it is that the CRUD functions should accept the full URL and not store the hosts and paths in redux store. IMHO currying would bring unnecessary complexity.

**Comment by egeriis** [comment]
Personally I think that's an annoying convention, from an application developer perspective. Because it doesn't support me in building an application that is easily adaptable to changes. I.e. if I were to change the hostname of my API, I would have to search through all files that fetches data from it to update the hostname. In the way _redux-json-api_ currently handles this, I just have to change it once.

But I am definitely seeing some usefulness in being able to support multiple endpoints and paths.

**Comment by nitzansan** [comment]
Are there any news regarding this issue?
Is some kind of multiple-endpoint hosts going to be implemented anytime soon?

I personally think that both approaches mentions here should be available.
I agree with egeriis that it's generally more convenient to have to set the endpoint once.
However, full url should also be supported, for example we're using a complex microservices (all are "json-api"ed) architecture and some microservices might return a callback to a different microservice and we just want to fire this call without parsing the url for the host and setting it as part of our endpoint hosts.

Anyways, just wanted to know if there are any plans or news for this enhancement.

**Comment by egeriis** [comment]
@nitzansan The discussion appear to have stalled, and I haven't moved on it personally :) I'd be happy to review a PR if you have a good proposal for how this could work the best.

Feel free to discuss your proposal first, if you wish to :)

**Comment by nitzansan** [comment]
I will discuss with my team, maybe one of us will be able to get to it sometime soon.

**Comment by dakota** [comment]
Closing as stale. Feel free to reopen if you'd like to continue discussing this.
